version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-wordcount
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.1.3
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  db:
    image: mysql:5.7
    container_name: sqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - my-shared-network


networks:
  my-shared-network:
    driver: "bridge"